version: 2

jobs:
  build:
    docker:
    - image: circleci/python:3.7.1
    - image: circleci/postgres:11.3
    
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    working_directory: ~/AuthoTicket

    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        - v1-dependencies-
    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}
    - run:
        name: run tests
        command: |
          . venv/bin/activate
          pip install -r requirements.txt
          coverage run manage.py test && coverage report
          COVERALLS_REPO_TOKEN=${REPO_TOKEN} coveralls
    - store_artifacts:
        path: test-reports
        destination: test-reports
workflows:
  version: 2
  workflow:
    jobs:
    - build
