version: 2
orbs:
  coveralls: coveralls/coveralls@1.0.4

jobs:
  build:
    docker:
    - image: circleci/python@sha256:bf5eb2c51d47321acced9cc9506d8d0b71b2135e3c3b862516b0165d5b4586ef
    - image: circleci/postgres:11.3
    - image: circleci/redis:5.0.1
    
    # CircleCI maintains a library of pre-built images.
    # documented at https://circleci.com/docs/2.0/circleci-images/
    working_directory: ~/AuthoTicket

    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        - v1-dependencies-
    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}
    - run:
        name: run tests
        command: |
          . venv/bin/activate
          sudo pip install -r requirements.txt
          sudo coverage run manage.py test && coverage report
          COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN} coveralls
    - store_artifacts:
        path: test-reports
        destination: test-reports
workflows:
  version: 2
  workflow:
    jobs:
    - build
