version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
        environment:
          DEBUG: True
          EMAIL_HOST_USER: vicads01@gmail.com
          EMAIL_HOST_PASSWORD: Adupiotondo10
          SECRET_KEY: ce*vb^97z^fi8)h3_bcr-b=@c2b!xmq01c&o_bl)prv%=qy!j@

          CLOUD_NAME: victoradukwu
          CLOUDINARY_API_KEY: 297581248268948
          CLOUDINARY_API_SECRET: Oja1BPO4FNP39YfFrKkHKy1advw
          PAYSTACK_TEST_SECRET_KEY: sk_test_a4586c98a93bc4aa0ed99b9f0be74535c1216fb6
          PAYSTACK_TEST_PUBLICK_KEY: pk_test_54608f7d1306c0ff6496fb1db83715133c0d9bf0

          CELERY_BROKER_URL: 'redis://localhost'
          REDIS_URL: redis://127.0.0.1:6379/1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: victor
          POSTGRES_DB: autoticket
          POSTGRES_PASSWORD: victor

      - image: redis:5.0.2

    working_directory: ~/AutoTicket

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run test and coverage
          command: |
            . venv/bin/activate
            coverage run manage.py test && coverage report && coveralls
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
