# Generated by Django 2.1.7 on 2019-08-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.IntegerField(choices=[(1, 'active'), (0, 'cancelled')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.IntegerField(choices=[(1, 'active'), (0, 'cancelled')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 'paid'), (0, 'pending')], default=1, max_length=10),
        ),
    ]
