# Generated by Django 2.1.7 on 2019-03-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190320_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='passenger',
            field=models.CharField(max_length=100),
        ),
    ]
