# Generated by Django 2.1.7 on 2019-03-21 13:55

import app.utils.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190321_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_status',
            field=models.CharField(choices=[(app.utils.enums.PaymentStatus('paid'), 'paid'), (app.utils.enums.PaymentStatus('pending'), 'pending')], default=app.utils.enums.PaymentStatus('paid'), max_length=10),
        ),
    ]
