# Generated by Django 2.1.7 on 2019-09-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190907_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='payment_status',
        ),
    ]
