# Generated by Django 2.1.7 on 2019-03-21 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ticket_payment_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('seat_number', 'flight')},
        ),
    ]
